### ISSUE TITLE
Rollouts are now rolling back

### ISSUE THREAD

**Issue by jeremypumphrey** [silinternational/ecs-deploy#102]
I've been using ecs-deploy for over a year. Suddenly I'm getting a message that it is rolling back to previous versions. My rollouts never finished in 90 seconds so technically failed. Did the code change to roll back with failures now? How can I avoid this?

$ docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy --cluster CTRP-IntTest-Backend --service-name CTRP-ctrp_import_ct_api-INTTEST -i $DOCKER_IMAGE:$DATE
Unable to find image 'silintl/ecs-deploy:latest' locally
latest: Pulling from silintl/ecs-deploy
Status: Downloaded newer image for silintl/ecs-deploy:latest
Using image name: ctrp/ctrp_import_ct_api:05-01-17-1354
Current task definition: arn:aws:ecs:us-east-1:127516845550:task-definition/CTRP-ctrp_import_ct_api-INTTEST:146
New task definition: arn:aws:ecs:us-east-1:127516845550:task-definition/CTRP-ctrp_import_ct_api-INTTEST:147
Service updated successfully, new task definition running.
Waiting for service deployment to complete...
Rolling back to arn:aws:ecs:us-east-1:127516845550:task-definition/CTRP-ctrp_import_ct_api-INTTEST:146

**Comment by fillup** [comment]
@jeremypumphrey yes, this feature just rolled out today that if the deployment does not complete in the timeframe it rolls back. I'm sorry this is causing a problem for you, I'll update it to be an optional setting with new parameter. I my use case I set a longer timeout to ensure it is successful or otherwise consider the deployment a failure, this just makes it safer if it fails to start up for me.

**Comment by jeremypumphrey** [comment]
Other than increasing the -t to 10 minutes (time to roll out completely in my case), is there a flag to simply ignore the failure and not roll back?

**Comment by jeremypumphrey** [comment]
-ignorefailure or -norolloback

**Comment by fillup** [comment]
I'm adding the flag now, will be done shortly.

**Comment by fillup** [comment]
I think the default should be not to rollback since that is a breaking change for you and probably others, the flag will be needed to enable rollback.

**Comment by fillup** [comment]
Fixed in version 3.1, see #103

**Comment by fillup** [comment]
Docker image still building though...https://hub.docker.com/r/silintl/ecs-deploy/builds/

**Comment by jeremypumphrey** [comment]
I waited for 3.1 to complete and tested. Still seeing the rollback behaviour. 

$ docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy --cluster CTRP-IntTest-Backend --service-name CTRP-ctrp_import_ct_api-INTTEST -i $DOCKER_IMAGE:$DATE
Unable to find image 'silintl/ecs-deploy:latest' locally
latest: Pulling from silintl/ecs-deploy
Status: Downloaded newer image for silintl/ecs-deploy:latest
Using image name: ctrp/ctrp_import_ct_api:05-01-17-1536
Current task definition: arn:aws:ecs:us-east-1:127516845550:task-definition/CTRP-ctrp_import_ct_api-INTTEST:146
New task definition: arn:aws:ecs:us-east-1:127516845550:task-definition/CTRP-ctrp_import_ct_api-INTTEST:148
Service updated successfully, new task definition running.
Waiting for service deployment to complete...
Rolling back to arn:aws:ecs:us-east-1:127516845550:task-definition/CTRP-ctrp_import_ct_api-INTTEST:146

**Comment by fillup** [comment]
@jeremypumphrey I'm thinking you did not get 3.1, can you check the source in that image to see if the enable-rollback flag is present? I tested with and without the parameter and observed it behaved as expected.

**Comment by jeremypumphrey** [comment]
Apologies, there might have been a lag from when DockerHub said it was posted and when it could actually be pulled. Seems to be working as before again now:

Status: Downloaded newer image for silintl/ecs-deploy:latest
Using image name: fnlcr/nci-adult-match-ui:05-01-17-1552
Current task definition: arn:aws:ecs:us-east-1:127516845550:task-definition/AdultMATCH-nci-adult-match-ui-INTTEST:107
New task definition: arn:aws:ecs:us-east-1:127516845550:task-definition/AdultMATCH-nci-adult-match-ui-INTTEST:111
ERROR: New task definition not running within 90 seconds

**Comment by fillup** [comment]
Well, there was another place in the code that called the rollback function that I forgot to wrap in a condition for the flag so I just updated it and pushed 3.1.1. 

Again, sorry for the problems :-(
