### ISSUE TITLE
Multiple containers on task overwrites both images.

### ISSUE THREAD

**Issue by brycereitano** [silinternational/ecs-deploy#6]
When deploying a task definition that has two containers. The images on both containers will be overwritten by the image supplied through the cli. Causing two duplicate containers being deployed, which breaks if you have two services that require each other. i.e. httpd and memcached

**Comment by fillup** [comment]
@brycereitano I just merged in a change from @johnallen3d, can you see if that resolves this issue for you?

**Comment by dgehrett** [comment]
Was this change rolled into the latest docker image at https://hub.docker.com/r/silintl/ecs-deploy/ ?  I'm still seeing my other containers having their images being overwritten.
